### ISSUE TITLE
[CEP-19] REST API: Change of option only in case returns error

### ISSUE THREAD

**Issue by FlexUli** [codeclou/customfield-editor-plugin#19] opened 2017-01-13 14:33 UTC
If you change an option on in case (eg. from "foo here" to "Foo here"), the PUT request returns with an error:
{
          'message' => 'validation errors',
          'subCode' => '400000',
          'errors' => [
                        {
                          'name' => 'optionvalue',
                          'message' => 'This option value does already exist. Option values need to be unique.'
                        }
                      ],
          'statusCode' => '400'
        };

**Comment by clouless** [comment] 2017-01-13 14:40
I will include this in next major release.
For now try a workaround: rename to 'foo here X' and back to ' Foo Here'.

**Comment by FlexUli** [comment] 2017-01-13 15:14
Thanks.
I already implemented this workaround... it works.

**Comment by clouless** [comment] 2017-04-11 17:26
backlog items are closed until scheduled for next release.

**Comment by clouless** [comment] 2018-11-03 17:58
Duplicate of #58 [CEP-59]

**Closed by clouless** 2018-11-03 17:58 UTC
Labels: duplicate
