### ISSUE TITLE
[CEP-35] Context Permissions do not load when a permission is set to a non existing contextId (JavaScript Error)

### ISSUE THREAD

**Issue by jkorpa** [codeclou/customfield-editor-plugin#35] opened 2017-10-02 18:50 UTC
Hello!

I am the JIRA system admin for a JIRA Server 7.3.3 instance (on-prem) that has Customfield Editor Plugin version 1.3.0 installed.

When I go into Customfield Editor and select Permission Editor then click edit on field 'Product Name/Part Number', Context Permissions do not load. This problem only happens for 'Product Name/Part Number'.

![jira issue](https://user-images.githubusercontent.com/24598014/31093835-d84183e2-a767-11e7-903a-b567d13601ba.jpg)

Cordial Regards,

-JK

**Comment by clouless** [comment] 2017-10-02 18:54
Hi,

I will investigate this soon. Could be because of the slash, but I need to check what is going on in detail.
Could you provide maybe a screenshot of the [Browser Consoles Network Tab](https://www.youtube.com/watch?v=AXGB4tIRNgM)? You can grey out any specific stuff such as domain a.s.o. I am just interested in the HTTP Error code and of the REST Call.

thx.

**Comment by jkorpa** [comment] 2017-10-02 19:14
Hi!

Thanks for the quick response!

Attached is the screen cap as requested:

![jira issue](https://user-images.githubusercontent.com/24598014/31094786-33bfa278-a76b-11e7-81d9-743224a7db36.jpg)

Regards,

-JK

**Comment by clouless** [comment] 2017-10-02 20:07
ok that helps a lot, thx. Seems like a tiny javascript bug.
I will fix it in version 1.5.0. I hope to release to the end of the week.

**Comment by jkorpa** [comment] 2017-10-02 20:14
OK, sounds like a plan. Thanks again for looking into this so quickly!

-JK

**Comment by clouless** [comment] 2017-10-06 09:19
Hi JK

I am at the end of release preparation for 1.5.0 now and am looking into this issue now.

I cannot reproduce the case. I am thinking something else might be wrong.
I have the following ideas of what could be wrong:

 * (1) Context is broken
   * Did you write to the Database manually?
 * (2) JIRA BaseUrl Config incorrect
   * Health Check can tell us more.
 * (3) Some other error.

------

Could you please provide me the following screenshots to get further clues what is wrong, thx
 (You can grey out names/projects)

### Customfield Configuration for context

![image](https://user-images.githubusercontent.com/12599965/31271052-fc062ffe-aa86-11e7-9d28-bef124c8c9d5.png)

![image](https://user-images.githubusercontent.com/12599965/31271084-1af73426-aa87-11e7-96d8-614a96bb1c5d.png)

### Network Tab when loading Page

Usually all XHR Requests should have Status 200.

![image](https://user-images.githubusercontent.com/12599965/31271450-d5044c14-aa87-11e7-8f01-78e463148ae5.png)

I am especially interested, what the 
`/rest/jiracustomfieldeditorplugin/1/admin/customfields/{customFieldID}/contexts/permissions/extended` Endpoint returns:

![image](https://user-images.githubusercontent.com/12599965/31271402-ac01143c-aa87-11e7-8be1-c6e53102c31e.png)

### JIRA Health Check

![image](https://user-images.githubusercontent.com/12599965/31271662-998fb942-aa88-11e7-8941-f1151e6c5461.png)


----


If you want you can email me the screenshots to DISCLOSED
if you are concerned about privacy.

Sorry for the inconvenience, but without the screenshots, I cannot tell what exactly is wrong.

**Comment by clouless** [comment] 2017-10-07 08:34
To not block the release the error display Enhancement #37 will be released with v1.5.0
And once I can reproduce this bug, I will release an Bugfix Release.

**Comment by clouless** [comment] 2017-10-09 18:20
fixed in v1.5.1 released 2017-10-09 to marketplace => https://marketplace.atlassian.com/plugins/jiracustomfieldeditorplugin/versions#b157

**Closed by clouless** 2017-10-09 18:20 UTC
Labels: bug

**Comment by clouless** [comment] 2018-02-01 14:36
# WORKAROUND: Fix it  manually in JIRA < v7.5 installations

*CAUSE:* There is a contextPermission set for a context that does no longer exist

*SOLUTION:* Detele the contextPermission manually for the non existing context
